# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MichaelChang-Lab4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MichaelChang-Lab4
  pod "youtube-ios-player-helper", "~> 0.1.4"

  target 'MichaelChang-Lab4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MichaelChang-Lab4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
